const express = require('express');
const { spawn, execSync } = require('child_process');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
const readline = require('readline');
const multer = require('multer');
const AdmZip = require('adm-zip');
const Database = require('better-sqlite3');
const config = require('./config');

process.on('uncaughtException', (err) => { console.error('[UNCAUGHT]', err.stack || err); });
process.on('unhandledRejection', (err) => { console.error('[UNHANDLED]', err.stack || err); });
process.on('SIGTERM', () => { console.error('[SIGNAL] SIGTERM received'); });
process.on('SIGHUP', () => { console.error('[SIGNAL] SIGHUP received'); });
process.on('exit', (code) => { console.error('[EXIT] process exiting with code', code); });

const app = express();
app.use(express.json({ limit: '20mb' }));

const upload = multer({ dest: '/tmp/ccmobile-uploads/', limits: { fileSize: 300 * 1024 * 1024 }, defParamCharset: 'utf8' });

// Check if Claude Code CLI is authenticated
function isClaudeAuthed() {
  try {
    const credPath = path.join(HOME_DIR, '.claude', '.credentials.json');
    if (!fs.existsSync(credPath)) return false;
    const cred = JSON.parse(fs.readFileSync(credPath, 'utf8'));
    return !!(cred.claudeAiOauth?.accessToken || cred.apiKey);
  } catch { return false; }
}

// Setup API — accessible without auth, mounted at /setup (outside /api)
app.get('/setup/status', (req, res) => {
  let projectCount = 0;
  if (fs.existsSync(config.PROJECT_ROOT)) {
    projectCount = fs.readdirSync(config.PROJECT_ROOT, { withFileTypes: true }).filter(d => d.isDirectory() && !d.name.startsWith('.')).length;
  }
  const claudeCliFound = fs.existsSync(config.CLAUDE_CLI_PATH);
  const claudeAuthed = claudeCliFound && isClaudeAuthed();
  res.json({
    configured: config.HAS_ENV && projectCount > 0 && claudeAuthed,
    projectRoot: config.PROJECT_ROOT,
    claudeCli: config.CLAUDE_CLI_PATH,
    claudeCliFound,
    claudeAuthed,
    sandbox: config.USE_SANDBOX,
    projectCount
  });
});

app.post('/setup/save', express.json(), (req, res) => {
  const { projectRoot } = req.body;
  if (!projectRoot || !projectRoot.trim()) return res.status(400).json({ error: 'Project root is required' });
  const root = projectRoot.trim();
  if (!fs.existsSync(root)) {
    try { fs.mkdirSync(root, { recursive: true }); } catch (e) { return res.status(400).json({ error: `Cannot create directory: ${e.message}` }); }
  }
  const lines = [`# ccmobile Configuration (generated by setup wizard)`, `CCMOBILE_PROJECT_ROOT=${root}`];
  try {
    fs.writeFileSync(config.ENV_PATH, lines.join('\n') + '\n');
    res.json({ ok: true, note: 'Configuration saved. Please restart the server for changes to take effect.' });
  } catch (e) {
    res.status(500).json({ error: `Failed to write .env: ${e.message}` });
  }
});

// Auth: if ACCESS_KEY is set, require it; otherwise allow all requests
app.post('/api/auth', (req, res) => {
  if (!config.ACCESS_KEY) return res.json({ ok: true });
  const { key } = req.body;
  if (key === config.ACCESS_KEY) return res.json({ ok: true });
  res.status(401).json({ error: 'Invalid access key' });
});

app.use('/api', (req, res, next) => {
  if (!config.ACCESS_KEY) return next();
  if (req.headers['authorization'] === config.ACCESS_KEY) return next();
  res.status(401).json({ error: 'Unauthorized' });
});

app.use(express.static('application/public'));

const PROJECT_ROOT = config.PROJECT_ROOT;
const HOME_DIR = config.HOME_DIR;
const CLAUDE_SESSIONS_ROOT = config.CLAUDE_SESSIONS_ROOT;
const FILE_HISTORY_ROOT = config.FILE_HISTORY_ROOT;
const activeSessions = new Map();

// SQLite database (minimal — only session names and project notes)
const DB_PATH = path.join(__dirname, 'data', 'ccmobile.db');
if (!fs.existsSync(path.join(__dirname, 'data'))) fs.mkdirSync(path.join(__dirname, 'data'));
const db = new Database(DB_PATH);
db.pragma('journal_mode = WAL');

db.exec(`
  CREATE TABLE IF NOT EXISTS session_names (
    session_id TEXT PRIMARY KEY,
    name TEXT NOT NULL
  );
  CREATE TABLE IF NOT EXISTS project_notes (
    id TEXT PRIMARY KEY,
    project TEXT NOT NULL,
    content TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_notes_project ON project_notes(project);
`);

// Auto-cleanup stale sessions (no activity for 2 hours)
setInterval(() => {
  const cutoff = Date.now() - 2 * 60 * 60 * 1000;
  for (const [id, s] of activeSessions) {
    if ((s.lastActive || 0) < cutoff) activeSessions.delete(id);
  }
}, 10 * 60 * 1000);

// Convert project path to claude sessions dir name
function projectToSessionDir(projectPath) {
  return projectPath.replace(/\//g, '-').replace(/^-/, '-');
}

// Find CLAUDE.md with case-insensitive match
function findClaudeMd(dir) {
  try {
    const f = fs.readdirSync(dir).find(n => n.toLowerCase() === 'claude.md');
    return f ? path.join(dir, f) : null;
  } catch { return null; }
}

// Build project info object
function buildProjectInfo(fullPath, name) {
  const sessionDir = path.join(CLAUDE_SESSIONS_ROOT, projectToSessionDir(fullPath));
  let sessionCount = 0;
  if (fs.existsSync(sessionDir)) {
    sessionCount = fs.readdirSync(sessionDir).filter(f => f.endsWith('.jsonl')).length;
  }
  return {
    name, path: fullPath,
    hasGit: fs.existsSync(path.join(fullPath, '.git')) && (() => { try { execSync('git remote get-url origin', { cwd: fullPath, stdio: 'ignore' }); return true; } catch { return false; } })(),
    hasClaudeMd: !!findClaudeMd(fullPath),
    sessionCount
  };
}

// Build bwrap sandbox args for a project directory
function buildSandboxArgs(projectDir, claudeArgs) {
  return [
    '--ro-bind', '/usr', '/usr',
    '--ro-bind', '/lib', '/lib',
    '--ro-bind', '/lib64', '/lib64',
    '--ro-bind', '/bin', '/bin',
    '--ro-bind', '/sbin', '/sbin',
    '--ro-bind', '/etc', '/etc',
    '--ro-bind', '/run', '/run',
    '--dev', '/dev',
    '--proc', '/proc',
    '--bind', '/tmp', '/tmp',
    '--bind', projectDir, projectDir,
    '--bind', HOME_DIR + '/.claude', HOME_DIR + '/.claude',
    '--bind', HOME_DIR + '/.claude.json', HOME_DIR + '/.claude.json',
    '--ro-bind', HOME_DIR + '/.npm', HOME_DIR + '/.npm',
    '--ro-bind', HOME_DIR + '/.config', HOME_DIR + '/.config',
    '--ro-bind', HOME_DIR + '/.local', HOME_DIR + '/.local',
    '--chdir', projectDir,
    '--share-net',
    config.CLAUDE_CLI_PATH, ...claudeArgs
  ];
}

// Parse JSONL session file
function parseSessionJSONL(filePath) {
  return new Promise((resolve) => {
    const userMessages = new Map();
    const snapshotGroups = new Map();
    const allMessages = [];
    let customTitle = null;

    const rl = readline.createInterface({ input: fs.createReadStream(filePath), crlfDelay: Infinity });
    rl.on('line', (line) => {
      try {
        const obj = JSON.parse(line);
        if (obj.type === 'custom-title') {
          customTitle = obj.customTitle || null;
        }
        if (obj.type === 'user' && !obj.isMeta) {
          let content = obj.message?.content || '';
          if (Array.isArray(content)) content = content.find(b => b.type === 'text')?.text || '';
          if (typeof content === 'string' && !content.startsWith('<') && content.length > 2) {
            userMessages.set(obj.uuid, { content: content.substring(0, 120), timestamp: obj.timestamp });
            allMessages.push({ role: 'user', content, ts: obj.timestamp, uuid: obj.uuid });
          }
        }
        if (obj.type === 'assistant' && obj.message?.content) {
          let text = '';
          const tools = [];
          for (const block of obj.message.content) {
            if (block.type === 'text' && block.text) text += block.text;
            if (block.type === 'tool_use') tools.push({ name: block.name, input: block.input });
          }
          if (text || tools.length) {
            allMessages.push({ role: 'assistant', content: text, tools, ts: obj.timestamp });
          }
        }
        if (obj.type === 'file-history-snapshot' && obj.snapshot?.messageId) {
          snapshotGroups.set(obj.snapshot.messageId, obj.snapshot);
        }
      } catch {}
    });
    rl.on('close', () => resolve({ userMessages, snapshotGroups, allMessages, customTitle }));
  });
}

// Resolve project name to full path
function resolveProjectPath(projectName) {
  return path.join(PROJECT_ROOT, projectName);
}

// List all project directories
app.get('/api/projects', (req, res) => {
  if (!fs.existsSync(PROJECT_ROOT)) return res.json({ projects: [] });
  const dirs = fs.readdirSync(PROJECT_ROOT, { withFileTypes: true })
    .filter(d => d.isDirectory() && !d.name.startsWith('.'))
    .map(d => buildProjectInfo(path.join(PROJECT_ROOT, d.name), d.name));
  res.json({ projects: dirs });
});

// Read CLAUDE.md for a project
app.get('/api/projects/:name/claude-md', (req, res) => {
  const projectPath = resolveProjectPath(req.params.name);
  const mdPath = findClaudeMd(projectPath);
  if (!mdPath) return res.json({ exists: false, content: '' });
  res.json({ exists: true, content: fs.readFileSync(mdPath, 'utf8') });
});

// Write CLAUDE.md for a project
app.put('/api/projects/:name/claude-md', (req, res) => {
  const projectPath = resolveProjectPath(req.params.name);
  const mdPath = findClaudeMd(projectPath) || path.join(projectPath, 'CLAUDE.md');
  try {
    fs.writeFileSync(mdPath, req.body.content || '');
    res.json({ ok: true });
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

// List sessions for a project
app.get('/api/projects/:name/sessions', async (req, res) => {
  const projectPath = resolveProjectPath(req.params.name);
  const sessionDir = path.join(CLAUDE_SESSIONS_ROOT, projectToSessionDir(projectPath));
  if (!fs.existsSync(sessionDir)) return res.json([]);

  const jsonlFiles = fs.readdirSync(sessionDir).filter(f => f.endsWith('.jsonl'));
  const sessions = [];

  for (const file of jsonlFiles) {
    const sessionId = file.replace('.jsonl', '');
    const filePath = path.join(sessionDir, file);
    const stat = fs.statSync(filePath);
    try {
      const { allMessages, customTitle } = await parseSessionJSONL(filePath);
      if (allMessages.length === 0) continue;
      const firstUser = allMessages.find(m => m.role === 'user');
      const last = allMessages[allMessages.length - 1];
      sessions.push({
        sessionId,
        firstMessage: firstUser ? firstUser.content.substring(0, 120) : null,
        customTitle: customTitle || null,
        lastTimestamp: last.ts || stat.mtime.toISOString(),
        messageCount: allMessages.filter(m => m.role === 'user').length,
        mtime: stat.mtime.getTime()
      });
    } catch {}
  }

  sessions.sort((a, b) => b.mtime - a.mtime);
  if (sessions.length) {
    const nameRows = db.prepare('SELECT session_id, name FROM session_names WHERE session_id IN (' + sessions.map(() => '?').join(',') + ')').all(...sessions.map(s => s.sessionId));
    const nameMap = Object.fromEntries(nameRows.map(r => [r.session_id, r.name]));
    for (const s of sessions) s.customName = nameMap[s.sessionId] || s.customTitle || null;
  }
  res.json(sessions);
});

// Rename a session
app.put('/api/sessions/:sessionId/name', (req, res) => {
  const { sessionId } = req.params;
  const { name, project } = req.body;
  const trimmed = (name || '').trim();
  if (!trimmed) {
    db.prepare('DELETE FROM session_names WHERE session_id = ?').run(sessionId);
  } else {
    db.prepare('INSERT OR REPLACE INTO session_names (session_id, name) VALUES (?, ?)').run(sessionId, trimmed);
  }
  if (project) {
    const projectPath = resolveProjectPath(project);
    const sessionDir = path.join(CLAUDE_SESSIONS_ROOT, projectToSessionDir(projectPath));
    const jsonlPath = path.join(sessionDir, `${sessionId}.jsonl`);
    if (fs.existsSync(jsonlPath)) {
      const titleLine = JSON.stringify({ type: 'custom-title', customTitle: trimmed || '', sessionId }) + '\n';
      try { fs.appendFileSync(jsonlPath, titleLine); } catch {}
    }
  }
  res.json({ ok: true });
});

// Get session messages (paginated)
app.get('/api/sessions/:sessionId/messages', async (req, res) => {
  const { sessionId } = req.params;
  const projectName = req.query.project;
  if (!projectName) return res.status(400).json({ error: 'project query param required' });

  const limit = Math.min(parseInt(req.query.limit) || 50, 200);
  const before = req.query.before != null ? parseInt(req.query.before) : null;

  const projectPath = resolveProjectPath(projectName);
  const sessionDir = path.join(CLAUDE_SESSIONS_ROOT, projectToSessionDir(projectPath));
  const filePath = path.join(sessionDir, `${sessionId}.jsonl`);
  if (!fs.existsSync(filePath)) return res.status(404).json({ error: 'Session not found' });

  const { allMessages } = await parseSessionJSONL(filePath);
  const total = allMessages.length;
  let end = before != null ? before : total;
  let start = Math.max(0, end - limit);
  const indexed = allMessages.slice(start, end).map((m, i) => ({ ...m, idx: start + i }));
  res.json({ messages: indexed, total, hasMore: start > 0 });
});

// Create a new chat session
app.post('/api/sessions', (req, res) => {
  const { projectName } = req.body;
  const projectPath = resolveProjectPath(projectName);
  if (!fs.existsSync(projectPath)) return res.status(404).json({ error: 'Project not found' });

  const id = crypto.randomUUID();
  activeSessions.set(id, { claudeSessionId: null, projectPath, projectName, lastActive: Date.now() });
  res.json({ id, projectPath, projectName });
});

// Resume an existing claude session
app.post('/api/sessions/resume', (req, res) => {
  const { projectName, claudeSessionId } = req.body;
  const projectPath = resolveProjectPath(projectName);
  if (!fs.existsSync(projectPath)) return res.status(404).json({ error: 'Project not found' });

  for (const [existingId, s] of activeSessions) {
    if (s.claudeSessionId === claudeSessionId && s.childProcess && !s.childProcess.killed) {
      s.lastActive = Date.now();
      return res.json({ id: existingId, claudeSessionId, projectPath, projectName, running: true });
    }
  }

  const id = crypto.randomUUID();
  activeSessions.set(id, { claudeSessionId, projectPath, projectName, lastActive: Date.now() });
  res.json({ id, claudeSessionId, projectPath, projectName, running: false });
});

// Send message and stream response via SSE
app.post('/api/sessions/:id/message', (req, res) => {
  const session = activeSessions.get(req.params.id);
  if (!session) return res.status(404).json({ error: 'Session not found' });
  session.lastActive = Date.now();

  const { message, images } = req.body;

  // Save images inside project dir (visible in bwrap sandbox)
  const tempFiles = [];
  if (images && images.length > 0) {
    const imgDir = path.join(session.projectPath, '.ccmobile-tmp');
    if (!fs.existsSync(imgDir)) fs.mkdirSync(imgDir, { recursive: true });
    for (const img of images) {
      const ext = img.mimeType === 'image/png' ? '.png' : img.mimeType === 'image/gif' ? '.gif' : '.jpg';
      const tmpPath = path.join(imgDir, `${crypto.randomUUID()}${ext}`);
      fs.writeFileSync(tmpPath, Buffer.from(img.data, 'base64'));
      tempFiles.push(tmpPath);
    }
  }

  let prompt = message || '';
  if (tempFiles.length > 0) {
    prompt += '\n\n' + tempFiles.map(f => `[Attached image: ${f}]`).join('\n');
  }

  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');
  res.setHeader('X-Accel-Buffering', 'no');

  let resAlive = true;
  function sseSend(data) {
    if (!resAlive) return;
    try { res.write(`data: ${JSON.stringify(data)}\n\n`); } catch { resAlive = false; }
  }

  const claudeArgs = ['-p', '--output-format', 'stream-json', '--verbose'];
  if (session.claudeSessionId) {
    claudeArgs.push('--resume', session.claudeSessionId);
  }
  claudeArgs.push('--dangerously-skip-permissions');

  let child;
  if (config.USE_SANDBOX) {
    const bwrapArgs = buildSandboxArgs(session.projectPath, claudeArgs);
    console.log(`[spawn] bwrap sandbox for ${session.projectPath}`);
    child = spawn(config.BWRAP_PATH, bwrapArgs, {
      env: { ...process.env, HOME: HOME_DIR },
      stdio: ['pipe', 'pipe', 'pipe'],
      detached: true
    });
  } else {
    console.log(`[spawn] direct (no sandbox) for ${session.projectPath}`);
    child = spawn(config.CLAUDE_CLI_PATH, claudeArgs, {
      cwd: session.projectPath,
      env: { ...process.env, HOME: HOME_DIR },
      stdio: ['pipe', 'pipe', 'pipe'],
      detached: true
    });
  }

  session.childProcess = child;

  child.stdin.write(prompt);
  child.stdin.end();

  function cleanupTempFiles() {
    for (const f of tempFiles) {
      try { fs.unlinkSync(f); } catch {}
    }
    const imgDir = path.join(session.projectPath, '.ccmobile-tmp');
    try { fs.rmSync(imgDir, { recursive: true, force: true }); } catch {}
  }

  let fullText = '';
  let buffer = '';

  child.on('error', (err) => {
    console.error('[spawn error]', err);
    sseSend({ type: 'error', text: err.message });
  });

  child.stdout.on('data', (chunk) => {
    buffer += chunk.toString();
    const lines = buffer.split('\n');
    buffer = lines.pop();

    for (const line of lines) {
      if (!line.trim()) continue;
      try {
        const evt = JSON.parse(line);

        if (evt.type === 'system' && evt.subtype === 'init') {
          session.claudeSessionId = evt.session_id;
          sseSend({ type: 'init', sessionId: evt.session_id });
        }
        else if (evt.type === 'assistant' && evt.message?.content) {
          for (const block of evt.message.content) {
            if (block.type === 'text') {
              fullText += block.text;
              sseSend({ type: 'text', text: block.text });
            } else if (block.type === 'tool_use') {
              sseSend({ type: 'tool_use', name: block.name, input: block.input });
            }
          }
        }
        else if (evt.type === 'result') {
          session.claudeSessionId = evt.session_id;
          if (evt.result && !fullText) fullText = evt.result;
          session._lastCost = evt.total_cost_usd;
          session._lastDuration = evt.duration_ms;
          sseSend({ type: 'done', text: evt.result, cost: evt.total_cost_usd, duration: evt.duration_ms });
        }
      } catch {}
    }
  });

  child.stderr.on('data', (chunk) => {
    const errText = chunk.toString();
    console.error('[claude stderr]', errText);
    if (errText.trim()) {
      sseSend({ type: 'error', text: errText });
    }
  });

  child.on('close', (code, signal) => {
    console.log(`[claude exit] code=${code}, signal=${signal}, text length=${fullText.length}`);
    session.childProcess = null;
    cleanupTempFiles();
    session.lastResult = { text: fullText, cost: session._lastCost, duration: session._lastDuration };
    sseSend({ type: 'end' });
    if (resAlive) { try { res.end(); } catch {} }
    resAlive = false;
    if (session._waitCallbacks) {
      for (const cb of session._waitCallbacks) cb();
      session._waitCallbacks = null;
    }
  });

  res.on('close', () => {
    resAlive = false;
  });
});

// Wait for session result (reconnection endpoint)
app.get('/api/sessions/:id/wait', (req, res) => {
  const session = activeSessions.get(req.params.id);
  if (!session) return res.status(404).json({ error: 'Session not found' });

  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');
  res.setHeader('X-Accel-Buffering', 'no');

  if (!session.childProcess) {
    try {
      const r = session.lastResult || {};
      res.write(`data: ${JSON.stringify({ type: 'done', text: r.text || '', cost: r.cost, duration: r.duration })}\n\n`);
      res.write(`data: ${JSON.stringify({ type: 'end' })}\n\n`);
      res.end();
    } catch {}
    return;
  }

  if (!session._waitCallbacks) session._waitCallbacks = [];
  let waitAlive = true;
  const onDone = () => {
    if (!waitAlive) return;
    waitAlive = false;
    try {
      const r = session.lastResult || {};
      res.write(`data: ${JSON.stringify({ type: 'done', text: r.text || '', cost: r.cost, duration: r.duration })}\n\n`);
      res.write(`data: ${JSON.stringify({ type: 'end' })}\n\n`);
      res.end();
    } catch {}
  };
  session._waitCallbacks.push(onDone);

  res.on('close', () => {
    waitAlive = false;
    if (session._waitCallbacks) {
      session._waitCallbacks = session._waitCallbacks.filter(cb => cb !== onDone);
    }
  });
});

// Stop a running Claude process
app.post('/api/sessions/:id/stop', (req, res) => {
  const session = activeSessions.get(req.params.id);
  if (!session) return res.status(404).json({ error: 'Session not found' });
  if (session.childProcess && !session.childProcess.killed) {
    console.log(`[stop] sending SIGINT to session ${req.params.id}, pid=${session.childProcess.pid}`);
    try {
      process.kill(-session.childProcess.pid, 'SIGINT');
    } catch (e) {
      session.childProcess.kill('SIGINT');
    }
    res.json({ ok: true });
  } else {
    res.json({ ok: false, reason: 'No running process' });
  }
});

// ========== File Tree & Upload ==========

app.get('/api/projects/:name/files', (req, res) => {
  const projectPath = resolveProjectPath(req.params.name);
  if (!fs.existsSync(projectPath)) return res.status(404).json({ error: 'Project not found' });

  const relDir = req.query.path || '';
  const absDir = path.join(projectPath, relDir);
  if (!absDir.startsWith(projectPath)) return res.status(400).json({ error: 'Invalid path' });
  if (!fs.existsSync(absDir) || !fs.statSync(absDir).isDirectory()) return res.status(404).json({ error: 'Directory not found' });

  const HIDDEN = new Set(['.git', 'node_modules', '.ccmobile-tmp', '__pycache__', '.next', '.cache', 'dist']);
  try {
    const entries = fs.readdirSync(absDir, { withFileTypes: true })
      .filter(e => !HIDDEN.has(e.name) && !e.name.startsWith('.git'))
      .map(e => ({ name: e.name, isDir: e.isDirectory() }))
      .sort((a, b) => {
        if (a.isDir !== b.isDir) return a.isDir ? -1 : 1;
        return a.name.localeCompare(b.name);
      });
    res.json({ path: relDir, entries });
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

app.post('/api/projects/:name/upload', upload.array('files', 20), (req, res) => {
  const projectPath = resolveProjectPath(req.params.name);
  if (!fs.existsSync(projectPath)) return res.status(404).json({ error: 'Project not found' });

  const targetDir = req.body.targetDir || '';
  const absTarget = path.join(projectPath, targetDir);
  if (!absTarget.startsWith(projectPath)) return res.status(400).json({ error: 'Invalid path' });
  if (!fs.existsSync(absTarget) || !fs.statSync(absTarget).isDirectory()) return res.status(400).json({ error: 'Target directory not found' });

  if (!req.files || req.files.length === 0) return res.status(400).json({ error: 'No files uploaded' });

  const uploaded = [];
  for (const file of req.files) {
    const destPath = path.join(absTarget, file.originalname);
    if (fs.existsSync(destPath) && fs.statSync(destPath).isDirectory()) {
      try { fs.unlinkSync(file.path); } catch {}
      continue;
    }
    fs.renameSync(file.path, destPath);
    uploaded.push(file.originalname);
  }
  res.json({ ok: true, uploaded });
});

app.post('/api/projects/:name/upload-zip', upload.single('file'), (req, res) => {
  const projectPath = resolveProjectPath(req.params.name);
  if (!fs.existsSync(projectPath)) return res.status(404).json({ error: 'Project not found' });
  if (!req.file) return res.status(400).json({ error: 'No file uploaded' });

  const targetDir = req.body.targetDir || '';
  const absTarget = path.join(projectPath, targetDir);
  if (!absTarget.startsWith(projectPath)) return res.status(400).json({ error: 'Invalid path' });

  try {
    let folderName = path.basename(req.file.originalname, path.extname(req.file.originalname));
    if (!folderName) folderName = 'uploaded';
    const extractDir = path.join(absTarget, folderName);
    fs.mkdirSync(extractDir, { recursive: true });
    const zip = new AdmZip(req.file.path);
    zip.extractAllTo(extractDir, true);
    fs.unlinkSync(req.file.path);
    res.json({ ok: true, folder: folderName });
  } catch (e) {
    if (req.file.path && fs.existsSync(req.file.path)) fs.unlinkSync(req.file.path);
    res.status(500).json({ error: 'Failed to extract zip: ' + e.message });
  }
});

// ========== Git Commit & Push ==========

function gitExec(args, projectPath) {
  return execSync(`git ${args}`, { cwd: projectPath, encoding: 'utf8', timeout: 30000 });
}

app.get('/api/projects/:name/git-status', (req, res) => {
  const projectPath = resolveProjectPath(req.params.name);
  if (!fs.existsSync(path.join(projectPath, '.git'))) return res.status(400).json({ error: 'Not a git repo' });

  try {
    const status = gitExec('status --porcelain', projectPath);
    const files = status.trim().split('\n').filter(Boolean).map(line => ({
      status: line.substring(0, 2).trim(),
      file: line.substring(3)
    }));
    const branch = gitExec('branch --show-current', projectPath).trim();
    let hasRemote = false;
    try { gitExec('remote get-url origin', projectPath); hasRemote = true; } catch {}
    res.json({ files, branch, hasRemote });
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

app.post('/api/projects/:name/git-push', (req, res) => {
  const projectPath = resolveProjectPath(req.params.name);
  if (!fs.existsSync(path.join(projectPath, '.git'))) return res.status(400).json({ error: 'Not a git repo' });

  const commitMsg = req.body.message || 'Update from ccmobile';

  try {
    execSync('git add -A', { cwd: projectPath, encoding: 'utf8' });
    const result = require('child_process').spawnSync('git', ['commit', '-m', commitMsg], { cwd: projectPath, encoding: 'utf8' });
    if (result.status !== 0) throw new Error(result.stderr || 'Commit failed');

    let pushed = false;
    let hasRemote = false;
    try { gitExec('remote get-url origin', projectPath); hasRemote = true; } catch {}
    if (hasRemote) {
      try { gitExec('push', projectPath); pushed = true; } catch {}
    }
    res.json({ ok: true, pushed, hasRemote });
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

// ========== Rewind ==========

app.get('/api/sessions/:sessionId/rewind-points', async (req, res) => {
  const { sessionId } = req.params;
  const projectName = req.query.project;
  if (!projectName) return res.status(400).json({ error: 'project query param required' });

  const projectPath = resolveProjectPath(projectName);
  const sessionDir = path.join(CLAUDE_SESSIONS_ROOT, projectToSessionDir(projectPath));
  const filePath = path.join(sessionDir, `${sessionId}.jsonl`);
  if (!fs.existsSync(filePath)) return res.status(404).json({ error: 'Session not found' });

  const { userMessages, snapshotGroups } = await parseSessionJSONL(filePath);

  const points = [];
  for (const [msgId, snapshot] of snapshotGroups) {
    const userMsg = userMessages.get(msgId);
    if (!userMsg) continue;
    const fileCount = Object.keys(snapshot.trackedFileBackups || {}).filter(
      f => snapshot.trackedFileBackups[f].backupFileName != null
    ).length;
    if (fileCount === 0) continue;
    points.push({
      messageId: msgId,
      userContent: userMsg.content,
      timestamp: snapshot.timestamp || userMsg.timestamp,
      fileCount
    });
  }
  res.json(points);
});

app.post('/api/rewind', async (req, res) => {
  const { projectName, sessionId, messageId } = req.body;
  const projectPath = resolveProjectPath(projectName);
  if (!fs.existsSync(projectPath)) return res.status(404).json({ error: 'Project not found' });

  const sessionDir = path.join(CLAUDE_SESSIONS_ROOT, projectToSessionDir(projectPath));
  const filePath = path.join(sessionDir, `${sessionId}.jsonl`);
  if (!fs.existsSync(filePath)) return res.status(404).json({ error: 'Session not found' });

  const { snapshotGroups } = await parseSessionJSONL(filePath);
  const snapshot = snapshotGroups.get(messageId);
  if (!snapshot) return res.status(404).json({ error: 'Snapshot not found for this message' });

  const fileHistoryDir = path.join(FILE_HISTORY_ROOT, sessionId);
  const restored = [], deleted = [], errors = [];

  for (const [relPath, info] of Object.entries(snapshot.trackedFileBackups || {})) {
    const targetPath = path.join(projectPath, relPath);
    try {
      if (info.backupFileName) {
        const backupPath = path.join(fileHistoryDir, info.backupFileName);
        if (fs.existsSync(backupPath)) {
          fs.mkdirSync(path.dirname(targetPath), { recursive: true });
          fs.copyFileSync(backupPath, targetPath);
          restored.push(relPath);
        } else {
          errors.push(`backup missing: ${relPath}`);
        }
      } else {
        if (fs.existsSync(targetPath)) {
          fs.unlinkSync(targetPath);
          deleted.push(relPath);
        }
      }
    } catch (e) {
      errors.push(`${relPath}: ${e.message}`);
    }
  }

  console.log(`[rewind] restored=${restored.length}, deleted=${deleted.length}, errors=${errors.length}`);
  res.json({ ok: true, restored, deleted, errors });
});

app.delete('/api/sessions/:id', (req, res) => {
  activeSessions.delete(req.params.id);
  res.json({ ok: true });
});

app.delete('/api/sessions/:sessionId/delete', (req, res) => {
  const { sessionId } = req.params;
  const projectName = req.query.project;
  if (!projectName) return res.status(400).json({ error: 'project required' });
  const projectPath = resolveProjectPath(projectName);
  const sessionDir = path.join(CLAUDE_SESSIONS_ROOT, projectToSessionDir(projectPath));
  const jsonlPath = path.join(sessionDir, `${sessionId}.jsonl`);
  try { if (fs.existsSync(jsonlPath)) fs.unlinkSync(jsonlPath); } catch {}
  try { db.prepare('DELETE FROM session_names WHERE session_id = ?').run(sessionId); } catch {}
  for (const [id, s] of activeSessions) {
    if (s.claudeSessionId === sessionId) { activeSessions.delete(id); break; }
  }
  res.json({ ok: true });
});

// ========== Project Notes ==========

app.get('/api/projects/:name/notes', (req, res) => {
  const notes = db.prepare('SELECT * FROM project_notes WHERE project = ? ORDER BY created_at DESC').all(req.params.name);
  res.json(notes);
});

app.post('/api/projects/:name/notes', (req, res) => {
  const { content } = req.body;
  if (!content || !content.trim()) return res.status(400).json({ error: 'Content required' });
  const id = crypto.randomUUID();
  const now = new Date().toISOString();
  db.prepare('INSERT INTO project_notes (id, project, content, created_at, updated_at) VALUES (?, ?, ?, ?, ?)').run(id, req.params.name, content.trim(), now, now);
  res.json({ id, project: req.params.name, content: content.trim(), created_at: now, updated_at: now });
});

app.put('/api/projects/:name/notes/:id', (req, res) => {
  const { content } = req.body;
  if (!content || !content.trim()) return res.status(400).json({ error: 'Content required' });
  const now = new Date().toISOString();
  db.prepare('UPDATE project_notes SET content = ?, updated_at = ? WHERE id = ? AND project = ?').run(content.trim(), now, req.params.id, req.params.name);
  res.json({ ok: true });
});

app.delete('/api/projects/:name/notes/:id', (req, res) => {
  db.prepare('DELETE FROM project_notes WHERE id = ? AND project = ?').run(req.params.id, req.params.name);
  res.json({ ok: true });
});

// Startup preflight
const PORT = config.PORT;
console.log('');
console.log('  ╔══════════════════════════════════════╗');
console.log('  ║           ccmobile starting            ║');
console.log('  ╚══════════════════════════════════════╝');
console.log('');
if (fs.existsSync(config.CLAUDE_CLI_PATH)) {
  if (isClaudeAuthed()) {
    console.log(`  Claude CLI : ${config.CLAUDE_CLI_PATH} ✓ (authenticated)`);
  } else {
    console.log(`  Claude CLI : ${config.CLAUDE_CLI_PATH} ✓ (not logged in)`);
    console.log(`               Run: claude   to authenticate`);
  }
} else {
  console.log(`  Claude CLI : not found ✗`);
  console.log(`               Install: npm install -g @anthropic-ai/claude-code`);
}
console.log(`  Sandbox    : ${config.USE_SANDBOX ? 'enabled (bwrap)' : 'disabled (direct mode)'}`);
if (!fs.existsSync(PROJECT_ROOT)) {
  fs.mkdirSync(PROJECT_ROOT, { recursive: true });
  console.log(`  Projects   : ${PROJECT_ROOT} (created, empty)`);
} else {
  const pCount = fs.readdirSync(PROJECT_ROOT, { withFileTypes: true }).filter(d => d.isDirectory() && !d.name.startsWith('.')).length;
  console.log(`  Projects   : ${PROJECT_ROOT} (${pCount} projects)`);
}
if (!config.HAS_ENV) {
  console.log(`  Config     : no .env file — open browser to run setup wizard`);
} else {
  console.log(`  Config     : .env loaded ✓`);
}
console.log('');
app.listen(PORT, '0.0.0.0', () => {
  console.log(`  → http://localhost:${PORT}`);
  console.log('');
});
